# Generated by Django 6.0.2 on 2026-02-18 16:25

import django.db.models.deletion
import blog.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, db_comment="User's profile picture", help_text='A imagem que aparece junto com seus posts', upload_to=blog.models.user_profile_picture_path, verbose_name="User's profile picture")),
                ('bio', models.TextField(blank=True, help_text='Escreva um pouco sobre você', max_length=1000, verbose_name="User's biography")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Owner of this profile')),
            ],
        ),
    ]
