# Generated by Django 6.0.2 on 2026-02-19 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, db_comment="User's biografy", help_text='Escreva um pouco sobre você', max_length=1000, verbose_name="User's biography"),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_comment='The text of the post', help_text='Escreva aqui o que você quer desabafar', max_length=5000, verbose_name='The text of the post')),
                ('published_date', models.DateTimeField(auto_now_add=True, db_comment='Date the post was published', help_text='Data de criação do desabafo', verbose_name='Date the post was published')),
                ('last_edited', models.DateTimeField(auto_now=True, db_comment='Date the post was last edited', help_text='Data da última edição do desabafo', verbose_name='Date the post was last edited')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='The user that made the post')),
            ],
        ),
    ]
