# Generated by Django 6.0.2 on 2026-02-19 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options_alter_userprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(db_comment='The user that made the post', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='The user that made the post'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_comment='The text of the post', help_text='Escreva aqui o que você quer desabafar', max_length=500, verbose_name='Text of the comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Date the comment was made', help_text='Data de criação do comentário', verbose_name='Date the comment was made')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Date the comment was last edited', help_text='Data da última edição do comentário', verbose_name='Date the comment was last edited')),
                ('author', models.ForeignKey(db_comment='User that wrote the comment', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Author of the comment')),
                ('post', models.ForeignKey(db_comment='Post the comment was made on', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.post', verbose_name='Post the comment was made on')),
            ],
        ),
    ]
