# Generated by Django 6.0.2 on 2026-03-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Escreva aqui o que você quer comentar', max_length=500, verbose_name='Text of the comment'),
        ),
    ]
